#include "gfx_font_outline.h"

#include <stdlib.h>
#include <string.h>

/* stb_truetype carries an explicit "do not use on untrusted font files"
 * warning. The only data it ever sees here is gfx_font_faces.h, which is a
 * compile-time constant array generated by tools/gen_font_header.py from a
 * subsetted upstream release. No font bytes reach this module at runtime. */
#define STBTT_STATIC
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include "gfx_font_faces.h"

/* Alpha at or above this counts as ROM ink when deriving a glyph's box. The
 * ROM's own antialiasing fringe sits below it, so the box tracks the solid
 * core of the letter rather than its halo. */
#define INK_THRESHOLD 96

/* How far a glyph may be stretched or compressed horizontally away from its
 * natural width in order to match the ROM's ink width. See the header. */
#define WIDTH_STRETCH_LIMIT 1.15f

/* Reference pixel height used to measure a glyph's natural proportions before
 * solving for the real scale. Large enough that the integer box from
 * stbtt_GetGlyphBitmapBox has negligible quantisation error at this step; the
 * box is re-solved at the real scale further down, because the extrapolation
 * is not exact. */
#define MEASURE_PIXELS 256.0f

typedef struct FaceState {
    stbtt_fontinfo info;
    bool ready;
    bool failed;
} FaceState;

static FaceState g_small;
static FaceState g_subtitle;

static uint8_t *g_glyph_buf;
static size_t g_glyph_cap;

uint32_t gfx_font_outline_clipped_texels;

static FaceState *face_state(GfxFontFace face) {
    switch (face) {
    case GFX_FONT_FACE_SMALL:
        return &g_small;
    case GFX_FONT_FACE_SUBTITLE:
        return &g_subtitle;
    default:
        return NULL;
    }
}

static const uint8_t *face_bytes(GfxFontFace face, size_t *size) {
    switch (face) {
    case GFX_FONT_FACE_SMALL:
        *size = MDKR_FONT_FACE_SMALL_ttf_size;
        return MDKR_FONT_FACE_SMALL_ttf;
    case GFX_FONT_FACE_SUBTITLE:
        *size = MDKR_FONT_FACE_SUBTITLE_ttf_size;
        return MDKR_FONT_FACE_SUBTITLE_ttf;
    default:
        *size = 0;
        return NULL;
    }
}

static stbtt_fontinfo *face_info(GfxFontFace face) {
    FaceState *state = face_state(face);
    const uint8_t *bytes;
    size_t size;

    if (state == NULL || state->failed) {
        return NULL;
    }
    if (state->ready) {
        return &state->info;
    }
    bytes = face_bytes(face, &size);
    if (bytes == NULL || size == 0 ||
        stbtt_InitFont(&state->info, bytes,
                       stbtt_GetFontOffsetForIndex(bytes, 0)) == 0) {
        state->failed = true;
        return NULL;
    }
    state->ready = true;
    return &state->info;
}

bool gfx_font_outline_available(GfxFontFace face) {
    return face_info(face) != NULL;
}

size_t gfx_font_outline_output_bytes(uint32_t width, uint32_t height,
                                     uint32_t upscale) {
    uint64_t pixels;

    if (width == 0 || height == 0 || upscale == 0) {
        return 0;
    }
    pixels = (uint64_t)width * upscale * (uint64_t)height * upscale;
    if (pixels > (uint64_t)SIZE_MAX / 4u) {
        return 0;
    }
    return (size_t)(pixels * 4u);
}

static bool ensure_glyph_buf(size_t bytes) {
    uint8_t *grown;

    if (bytes == 0) {
        return false;
    }
    if (bytes <= g_glyph_cap) {
        return g_glyph_buf != NULL;
    }
    grown = (uint8_t *)realloc(g_glyph_buf, bytes);
    if (grown == NULL) {
        return false;
    }
    g_glyph_buf = grown;
    g_glyph_cap = bytes;
    return true;
}

/* Bounding box of the region's ink, in region-local coordinates. Returns false
 * when the cell holds nothing (a space). */
static bool region_ink_box(const uint8_t *source, uint32_t width,
                           uint32_t height, const GfxFontAtlasRegion *region,
                           uint32_t *out_x0, uint32_t *out_y0,
                           uint32_t *out_x1, uint32_t *out_y1) {
    uint32_t x0 = region->width;
    uint32_t y0 = region->height;
    uint32_t x1 = 0;
    uint32_t y1 = 0;
    bool found = false;

    for (uint32_t y = 0; y < region->height; y++) {
        uint32_t sy = (uint32_t)region->y + y;
        if (sy >= height) {
            break;
        }
        for (uint32_t x = 0; x < region->width; x++) {
            uint32_t sx = (uint32_t)region->x + x;
            if (sx >= width) {
                break;
            }
            if (source[((size_t)sy * width + sx) * 4u + 3u] >= INK_THRESHOLD) {
                found = true;
                if (x < x0) {
                    x0 = x;
                }
                if (y < y0) {
                    y0 = y;
                }
                if (x + 1u > x1) {
                    x1 = x + 1u;
                }
                if (y + 1u > y1) {
                    y1 = y + 1u;
                }
            }
        }
    }
    if (!found) {
        return false;
    }
    *out_x0 = x0;
    *out_y0 = y0;
    *out_x1 = x1;
    *out_y1 = y1;
    return true;
}

/* Alpha-weighted mean colour of the region, so a tinted ROM glyph keeps its
 * tint. Falls back to white when the region is empty. */
static void region_colour(const uint8_t *source, uint32_t width,
                          uint32_t height, const GfxFontAtlasRegion *region,
                          uint8_t out_rgb[3]) {
    uint64_t sum[3] = {0, 0, 0};
    uint64_t weight = 0;

    for (uint32_t y = 0; y < region->height; y++) {
        uint32_t sy = (uint32_t)region->y + y;
        if (sy >= height) {
            break;
        }
        for (uint32_t x = 0; x < region->width; x++) {
            uint32_t sx = (uint32_t)region->x + x;
            if (sx >= width) {
                break;
            }
            const uint8_t *px = &source[((size_t)sy * width + sx) * 4u];
            uint64_t a = px[3];
            sum[0] += (uint64_t)px[0] * a;
            sum[1] += (uint64_t)px[1] * a;
            sum[2] += (uint64_t)px[2] * a;
            weight += a;
        }
    }
    if (weight == 0) {
        out_rgb[0] = out_rgb[1] = out_rgb[2] = 255;
        return;
    }
    for (int i = 0; i < 3; i++) {
        out_rgb[i] = (uint8_t)(sum[i] / weight);
    }
}

/* Nearest-neighbour copy of a ROM cell into the upscaled output. This is the
 * per-glyph safety net: an outline we cannot draw degrades to exactly what
 * ships today rather than to a hole in the text. */
static void blit_region_nearest(const uint8_t *source, uint32_t width,
                                uint32_t height, uint32_t upscale,
                                const GfxFontAtlasRegion *region,
                                uint8_t *output, uint32_t out_w) {
    for (uint32_t y = 0; y < (uint32_t)region->height * upscale; y++) {
        uint32_t sy = (uint32_t)region->y + y / upscale;
        uint32_t dy = (uint32_t)region->y * upscale + y;
        if (sy >= height) {
            break;
        }
        for (uint32_t x = 0; x < (uint32_t)region->width * upscale; x++) {
            uint32_t sx = (uint32_t)region->x + x / upscale;
            uint32_t dx = (uint32_t)region->x * upscale + x;
            if (sx >= width) {
                break;
            }
            memcpy(&output[((size_t)dy * out_w + dx) * 4u],
                   &source[((size_t)sy * width + sx) * 4u], 4u);
        }
    }
}

static bool render_glyph(stbtt_fontinfo *info, int codepoint,
                         const GfxFontAtlasRegion *region, uint32_t upscale,
                         uint32_t ink_x0, uint32_t ink_y0, uint32_t ink_x1,
                         uint32_t ink_y1, const uint8_t rgb[3],
                         uint8_t *output, uint32_t out_w, uint32_t out_h) {
    int glyph = stbtt_FindGlyphIndex(info, codepoint);
    float measure, scale_x, scale_y, natural_w, want_w;
    int mx0, my0, mx1, my1;
    int box_w, box_h;
    uint32_t target_w = (ink_x1 - ink_x0) * upscale;
    uint32_t target_h = (ink_y1 - ink_y0) * upscale;
    /* The glyph is laid down starting at the ROM ink's left inset, so the width
     * still available to it is what remains of the cell from there -- not the
     * whole cell. Clamping to the whole cell would let a wide glyph in an inset
     * cell run past the right edge, where the write loop's cell guard would
     * silently trim it. */
    uint32_t cell_limit = ((uint32_t)region->width - ink_x0) * upscale;
    uint32_t dst_w, origin_x, origin_y;

    if (glyph == 0 || target_w == 0 || target_h == 0) {
        return false;
    }

    measure = stbtt_ScaleForPixelHeight(info, MEASURE_PIXELS);
    stbtt_GetGlyphBitmapBox(info, glyph, measure, measure, &mx0, &my0, &mx1,
                            &my1);
    box_w = mx1 - mx0;
    box_h = my1 - my0;
    if (box_w <= 0 || box_h <= 0) {
        return false;
    }

    /* Height fit is exact; width follows the ROM within the stretch bound. */
    scale_y = measure * (float)target_h / (float)box_h;
    natural_w = (float)box_w * (float)target_h / (float)box_h;
    want_w = (float)target_w;
    if (want_w > natural_w * WIDTH_STRETCH_LIMIT) {
        want_w = natural_w * WIDTH_STRETCH_LIMIT;
    } else if (want_w < natural_w / WIDTH_STRETCH_LIMIT) {
        want_w = natural_w / WIDTH_STRETCH_LIMIT;
    }
    if (want_w > (float)cell_limit) {
        want_w = (float)cell_limit;      /* never clip against the cell */
    }
    dst_w = (uint32_t)(want_w + 0.5f);
    if (dst_w == 0) {
        dst_w = 1;
    }
    scale_x = measure * want_w / (float)box_w;

    /*
     * The box above was measured at MEASURE_PIXELS and extrapolated linearly,
     * but stbtt's integer box at the final scale is not the linearly scaled
     * box -- it can round to one more row or column. Rendering that into a
     * bitmap sized from the extrapolation lets the rasteriser drop the extra
     * row: the foot of a descender, or the right stem of 'W'.
     *
     * Growing the bitmap instead is not an option, because the glyph is
     * anchored at its ink origin and a taller bitmap would run past the bottom
     * of the cell. So solve the other way: shrink the scale until the box at
     * that scale really does fit the target. Undershooting by a pixel leaves a
     * transparent edge, which is invisible; overshooting truncates the letter.
     * The ratio step is always <= 1, so this converges immediately in practice.
     */
    for (int pass = 0; pass < 4; pass++) {
        int fx0, fy0, fx1, fy1;
        int fit_w, fit_h;

        stbtt_GetGlyphBitmapBox(info, glyph, scale_x, scale_y, &fx0, &fy0,
                                &fx1, &fy1);
        fit_w = fx1 - fx0;
        fit_h = fy1 - fy0;
        if (fit_w <= (int)dst_w && fit_h <= (int)target_h) {
            break;
        }
        if (fit_w > (int)dst_w) {
            scale_x *= (float)dst_w / (float)fit_w;
        }
        if (fit_h > (int)target_h) {
            scale_y *= (float)target_h / (float)fit_h;
        }
    }

    if (!ensure_glyph_buf((size_t)dst_w * target_h)) {
        return false;
    }
    memset(g_glyph_buf, 0, (size_t)dst_w * target_h);
    stbtt_MakeGlyphBitmap(info, g_glyph_buf, (int)dst_w, (int)target_h,
                          (int)dst_w, scale_x, scale_y, glyph);

    /* Centre the fitted glyph in the ROM's ink box: left-aligning a narrower
     * face piles all the slack on one side and the line goes ragged. */
    origin_x = ((uint32_t)region->x + ink_x0) * upscale;
    if (target_w > dst_w) {
        origin_x += (target_w - dst_w) / 2u;
    }
    origin_y = ((uint32_t)region->y + ink_y0) * upscale;

    for (uint32_t y = 0; y < target_h; y++) {
        uint32_t dy = origin_y + y;
        if (dy >= out_h) {
            break;
        }
        for (uint32_t x = 0; x < dst_w; x++) {
            uint32_t dx = origin_x + x;
            uint8_t coverage = g_glyph_buf[(size_t)y * dst_w + x];
            uint8_t *dstpx;
            if (dx >= out_w) {
                break;
            }
            /* Stay inside the registered cell: a neighbouring glyph's texels
             * are one texrect away and must never be touched. */
            if (dx < (uint32_t)region->x * upscale ||
                dx >= ((uint32_t)region->x + region->width) * upscale ||
                dy < (uint32_t)region->y * upscale ||
                dy >= ((uint32_t)region->y + region->height) * upscale) {
                /* The guard is a backstop, not a policy: the fit is supposed to
                 * keep every glyph inside its cell, so anything trimmed here is
                 * a clipped letter. Counted so a gate can assert it never
                 * happens rather than trusting the arithmetic above. */
                if (coverage != 0) {
                    gfx_font_outline_clipped_texels++;
                }
                continue;
            }
            if (coverage == 0) {
                continue;
            }
            dstpx = &output[((size_t)dy * out_w + dx) * 4u];
            dstpx[0] = rgb[0];
            dstpx[1] = rgb[1];
            dstpx[2] = rgb[2];
            dstpx[3] = coverage;
        }
    }
    return true;
}

bool gfx_font_outline_render_rgba(
    GfxFontFace face, const uint8_t *source, uint32_t width, uint32_t height,
    uint32_t upscale, const GfxFontAtlasRegion *regions, size_t region_count,
    uint8_t *output, size_t output_size) {
    stbtt_fontinfo *info = face_info(face);
    size_t needed = gfx_font_outline_output_bytes(width, height, upscale);
    uint32_t out_w = width * upscale;
    uint32_t out_h = height * upscale;

    if (info == NULL || source == NULL || output == NULL || needed == 0 ||
        output_size < needed || regions == NULL || region_count == 0) {
        return false;
    }

    memset(output, 0, needed);

    for (size_t index = 0; index < region_count; index++) {
        const GfxFontAtlasRegion *region = &regions[index];
        uint32_t x0, y0, x1, y1;
        uint8_t rgb[3];
        int codepoint;
        bool already_drawn = false;

        if (region->width == 0 || region->height == 0 ||
            (uint32_t)region->x >= width || (uint32_t)region->y >= height) {
            continue;
        }
        /*
         * One authored cell can serve two characters -- FunFont draws 'a' from
         * the 'A' cell -- and the registry now keys regions by character, so
         * both survive. Neither replaced face aliases any cell today, but two
         * glyphs rasterised into one rectangle would superimpose rather than
         * replace, so first-character-wins is settled here instead of resting
         * on that measurement. It also matches what the ROM does: an aliased
         * cell has one set of pixels serving both characters.
         */
        for (size_t prior = 0; prior < index; prior++) {
            if (regions[prior].x == region->x &&
                regions[prior].y == region->y &&
                regions[prior].width == region->width &&
                regions[prior].height == region->height) {
                already_drawn = true;
                break;
            }
        }
        if (already_drawn) {
            continue;
        }
        if (!region_ink_box(source, width, height, region, &x0, &y0, &x1,
                            &y1)) {
            continue;                    /* a space: nothing to draw */
        }
        region_colour(source, width, height, region, rgb);

        codepoint = 0x20 + (int)region->character;
        if (codepoint < 0x20 || codepoint > 0x7E ||
            !render_glyph(info, codepoint, region, upscale, x0, y0, x1, y1,
                          rgb, output, out_w, out_h)) {
            blit_region_nearest(source, width, height, upscale, region, output,
                                out_w);
        }
    }
    return true;
}

void gfx_font_outline_shutdown(void) {
    free(g_glyph_buf);
    g_glyph_buf = NULL;
    g_glyph_cap = 0;
    gfx_font_outline_clipped_texels = 0;
    /* The parsed handles point into constant data that outlives teardown, but
     * clearing them keeps a re-init after shutdown honest rather than relying
     * on that. */
    memset(&g_small, 0, sizeof(g_small));
    memset(&g_subtitle, 0, sizeof(g_subtitle));
}
